service: mdesign-backend
env: standard
runtime: nodejs20

instance_class: B2

entrypoint: npm run start:production

# vpc_access_connector:
#   name: projects/modern-design-ai/locations/us-central1/connectors/mdesign

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ''

manual_scaling:
  instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  HOST: '0.0.0.0'
  PORT: '8080'
  NODE_ENV: 'production'
  DEBUG: 'mdesign:*'
